### PR TITLE
Fix initialization of TLS connections

### LINKED ISSUE #705: Is this code supposed to work?
https://github.com/go-mysql-org/go-mysql/blob/master/client/conn.go#L87

`c.tlsConfig` can't be anything but nil at that point since the options array hasn't been applied to the connection yet

### PR DESCRIPTION
**Pull request by viciious**
The check for tlsConfig being non-nil was in the wrong place. Fixes #705

### CODE REVIEW

File: client/conn.go [hunk 1]
```diff
@@ -103,6 +98,12 @@ func ConnectWithDialer(ctx context.Context, network string, addr string, user st
 		options[i](c)
 	}
 
+	if c.tlsConfig != nil {
+		seq := c.Conn.Sequence
+		c.Conn = packet.NewTLSConn(conn)
+		c.Conn.Sequence = seq
```
Comment (lance6716) [inline client/conn.go:104]: `packet.NewConn(conn)` just created some buffer, it didn't write MySQL data so I think Sequence is untouched.

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: client/conn.go (hunk 1 above)
Comment (viciious) [reply client/conn.go:104]: Yet it could be modified via an option call since it's a public field
