### PR TITLE
test: remove time-based checking

### LINKED ISSUE #988: flaky test TestCachingSha2CacheTLS/TestCache
```
--- FAIL: TestCachingSha2CacheTLS (0.44s)
    --- FAIL: TestCachingSha2CacheTLS/TestCache (0.40s)
        caching_sha2_cache_test.go:163:
            	Error Trace:	/home/linux1/go-mysql/server/caching_sha2_cache_test.go:163
            	Error:      	"107" is not less than "50"
            	Test:       	TestCachingSha2CacheTLS/TestCache
```

### PR DESCRIPTION
**Pull request by lance6716**
close #988

check a counter to verify cache really takes effect

### CODE REVIEW

**Comment by lance6716** [comment]
@dveeden PTAL

File: server/caching_sha2_cache_test.go [hunk 1]
```diff
@@ -58,11 +60,11 @@ func TestCachingSha2CacheTLS(t *testing.T) {
 
 type RemoteThrottleProvider struct {
 	*InMemoryProvider
-	delay int // in milliseconds
+	getCredCallCnt atomic.Int64
```
Comment (dveeden) [inline server/caching_sha2_cache_test.go:63]:
```suggestion
	getCredCallCount atomic.Int64
```

**Review by dveeden — APPROVED** [review]
